### PR TITLE
Add a flake.nix

### PR DESCRIPTION
**Pull request by Freed-Wu**
Now I add a flake.nix and remove extension/Makefile.

```shell
$ nix build
$ tree $(readlink -f result)
 /nix/store/05j4jsfbz7gazsq5w5d3q2bbvlbnira6-gnome-shell-extension-g3kb-switch-1.2
├──  bin
│  └──  g3kb-switch
├──  lib
│  └──  libg3kbswitch.so
└──  share
   ├──  bash-completions
   │  └──  completions
   │     └──  g3kb-switch
   ├──  gnome-shell
   │  └──  extensions
   │     └──  g3kb-switch@g3kb-switch.org
   │        ├──  extension.js
   │        ├──  LICENSE
   │        └──  metadata.json
   ├──  man
   │  └──  man1
   │     └──  g3kb-switch.1.gz
   ├──  pkgconfig
   │  └──  g3kb-switch.pc
   └──  zsh
      └──  site-functions
         └──  _g3kb-switch
$ nix run . -- --help
g3kb-switch version 1.2
Usage: g3kb-switch [-p]      Show the current layout group
       g3kb-switch -l        Show available layout groups
       g3kb-switch -n        Switch to the next layout group
       g3kb-switch -s ARG    Switch to layout group ARG
       g3kb-switch -h        Show this message and exit
       g3kb-switch -v        Show the program version and exit
$ nix run
us
```

### CODE REVIEW

**Comment by lyokha** [comment]
> Perhaps we should split this commit to two commits, one is remove extension/Makefile, two is add flake.nix

This is up to you, I'm ok with a single commit.

I would also remove line *Build and install the extension.* with the following code snippet in README. And would split the new long line by shorter lines in CMakeLists.txt. :)

**Comment by Freed-Wu** [comment]
> I would also remove line Build and install the extension.

I have updated documents and split the long line of CMakeLists.txt in the first commit. :smile:

**Comment by lyokha** [comment]
Looks good! I'm not familiar wit Nix and want to invest some time to learn this. Thanks!

**Comment by lyokha** [comment]
Is it ready for release *1.3*?

**Pull request merged**
