### PR TITLE
Add BASH_COMPLETION_COMPLETIONSDIR and ZSH_COMPLETION_COMPLETIONSDIR

### PR DESCRIPTION
**Pull request by Freed-Wu**
Allow users to customize the directory of shell completions

Refer <https://github.com/NixOS/nixpkgs/pull/243032>

### CODE REVIEW

**Comment by lyokha** [comment]
Hmm, I merged but this won't work for basg completion as BASH_COMPLETION_FOUND may stay uninitialized and INSTALL won't work.

**Comment by lyokha** [comment]
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 31272e1..8e6d2f2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -14,8 +14,11 @@ PKG_SEARCH_MODULE(GIO REQUIRED gio-2.0)
 
 SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)
 
-set(BASH_COMPLETION_COMPLETIONSDIR "" CACHE STRING "the directory of bash completions, empty will use the default value coming from pkg-config")
-set(ZSH_COMPLETION_COMPLETIONSDIR "" CACHE STRING "the directory of zsh completions, empty will use the default value")
+SET(BASH_COMPLETION_COMPLETIONSDIR "" CACHE STRING
+    "The directory of bash completions, \
+    empty will use the default value coming from pkg-config")
+SET(ZSH_COMPLETION_COMPLETIONSDIR "" CACHE STRING
+    "The directory of zsh completions, empty will use the default value")
 
 OPTION(G3KBSWITCH_WITH_GNOME_SHELL_EXTENSION "Use Gnome Shell extension" ON)
 IF(G3KBSWITCH_WITH_GNOME_SHELL_EXTENSION)
@@ -37,7 +40,9 @@ ENDIF()
 
 OPTION(G3KBSWITCH_INSTALL_BASH_COMPLETION "Install bash completion script" ON)
 IF(G3KBSWITCH_INSTALL_BASH_COMPLETION)
-    IF(NOT BASH_COMPLETION_COMPLETIONSDIR)
+    IF(BASH_COMPLETION_COMPLETIONSDIR)
+        SET(BASH_COMPLETION_FOUND ON)
+    ELSE()
         FIND_PACKAGE(bash-completion)
     ENDIF()
     IF(BASH_COMPLETION_FOUND)
```

This patch install bash completion in all cases. I also formatted variable's descriptions to be less than 80 craracters long.

**Comment by Freed-Wu** [comment]
> your solution looks cleaner.

OK. Thanks for your commend.

Can we publish a new version today after fixing all PRs? I want to package the program to NixOS <https://github.com/NixOS/nixpkgs/pull/243032> :smile:

**Comment by lyokha** [comment]
> Can we publish a new version today after fixing all PRs? I want to package the program to NixOS https://github.com/NixOS/nixpkgs/pull/243032

Sure! I've also applied some formatting to the descriptions of the new cache variables in the latest commit.

**Pull request merged**
