### PR TITLE
Set cache for G3KBSWITCH_VIM_XKBSWITCH_LIB_PATH

### PR DESCRIPTION
**Pull request by Freed-Wu**
This PR should not effect the building result.

### CODE REVIEW

**Comment by Freed-Wu** [comment]
Perhpas we can change extension/Makefile to CMakeLists.txt?

**Comment by Freed-Wu** [comment]
> Perhpas we can change extension/Makefile to CMakeLists.txt?

```cmake
INSTALL(DIRECTORY extension/g3kb-switch@g3kb-switch.org DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/gnome-shell/extensions)
```

**Comment by lyokha** [comment]
> Can you invite me as collaborators? I think I can do something smile

I invited you.

**Comment by lyokha** [comment]
> > Perhpas we can change extension/Makefile to CMakeLists.txt?
> 
> ```cmake
> INSTALL(DIRECTORY extension/g3kb-switch@g3kb-switch.org DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/gnome-shell/extensions)
> ```

This should be wrapped in `IF(G3KBSWITCH_WITH_GNOME_SHELL_EXTENSION)`.

**Pull request merged**
